# Generated by Django 5.2.18 on 2026-10-07 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_qr_code', models.TextField(blank=True, default='')),
                ('raw_barcode', models.TextField(blank=True, default='', help_text='«Сырое» содержимое штрих-кода с этикетки (формат ЛИМС пока неизвестен).')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('is_expected', models.BooleanField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Скан инвентаризации',
                'verbose_name_plural': 'Сканы инвентаризации',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='ACTIVE', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сессия инвентаризации',
                'verbose_name_plural': 'Сессии инвентаризации',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('CONTAINER_MISSING', 'Тара отсутствует'), ('CONTAINER_MISPLACED', 'Тара не на своём месте'), ('CONTAINER_EXTRA', 'Лишняя тара'), ('SAMPLE_MISSING', 'Проба отсутствует'), ('SAMPLE_STATUS_MISMATCH', 'Статус пробы не совпадает')], max_length=50)),
                ('expected_value', models.TextField(blank=True, default='')),
                ('actual_value', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issues', to='storage.container')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Расхождение',
                'verbose_name_plural': 'Расхождения',
                'ordering': ['-created_at'],
            },
        ),
    ]
