# Generated by Django 5.2.18 on 2026-10-07 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='ACTIVE', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, help_text='Кто начал сессию.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия инвентаризации',
                'verbose_name_plural': 'Сессии инвентаризации',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_qr_code', models.TextField(blank=True, default='', help_text='«Сырое» содержимое QR-кода для аудита.')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('is_expected', models.BooleanField(blank=True, help_text='True — ожидалось, False — лишнее. NULL — ещё не рассчитано.', null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('sample', models.ForeignKey(blank=True, help_text='NULL — отсканировано что-то, чего нет в системе.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_scans', to='samples.sample')),
                ('scanned_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_scans', to='storage.container')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='inventory.inventorysession')),
            ],
            options={
                'verbose_name': 'Скан инвентаризации',
                'verbose_name_plural': 'Сканы инвентаризации',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['status'], name='inv_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['-started_at'], name='inv_session_started_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryscan',
            index=models.Index(fields=['session', '-scanned_at'], name='inv_scan_session_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryscan',
            index=models.Index(fields=['sample'], name='inv_scan_sample_idx'),
        ),
    ]
