# Generated by Django 5.2.18 on 2026-10-07 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('samples', '0001_initial'),
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryissue',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issues', to='samples.sample'),
        ),
        migrations.AddField(
            model_name='inventoryscan',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_scans', to='samples.sample'),
        ),
        migrations.AddField(
            model_name='inventoryscan',
            name='scanned_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_scans', to='storage.container'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryscan',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='inventory.inventorysession'),
        ),
        migrations.AddField(
            model_name='inventoryissue',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='inventory.inventorysession'),
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['status'], name='inv_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysession',
            index=models.Index(fields=['-started_at'], name='inv_session_started_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryscan',
            index=models.Index(fields=['session', '-scanned_at'], name='inv_scan_session_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryscan',
            index=models.Index(fields=['sample'], name='inv_scan_sample_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryissue',
            index=models.Index(fields=['session', 'issue_type'], name='inv_issue_session_type_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryissue',
            index=models.Index(fields=['resolved_at'], name='inv_issue_resolved_idx'),
        ),
    ]
