# Generated by Django 5.2.18 on 2026-10-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Название Н/З. До или после шифровки — зависит от order_type.', max_length=100)),
                ('order_type', models.CharField(choices=[('INCOMING', 'Входящий'), ('CODED', 'Зашифрованный')], help_text='INCOMING — до шифровки, CODED — после.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён')], default='ACTIVE', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_order', models.ForeignKey(blank=True, help_text='Парный Н/З: для INCOMING — зашифрованный, для CODED — входящий.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Наряд-заказ',
                'verbose_name_plural': 'Наряд-заказы',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('order_number', 'order_type'), name='work_order_unique_number_type'), models.CheckConstraint(condition=models.Q(('id', models.F('linked_order_id')), _negated=True), name='work_order_not_linked_to_self')],
            },
        ),
    ]
