# Generated by Django 5.2.18 on 2026-10-09 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_sample_options_and_more'),
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Участок (авто-определение по паттернам Н/З).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='samples.site'),
        ),
    ]
