# Generated by Django 5.2.18 on 2026-10-07 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, help_text='Роль пользователя. NULL — роль не назначена.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Тип действия: SCAN, MOVE, CREATE, UPDATE, DELETE', max_length=100)),
                ('entity_type', models.CharField(help_text='Тип сущности: Sample, Container, WorkOrder, ...', max_length=50)),
                ('entity_id', models.IntegerField(blank=True, help_text='ID сущности, к которой относится действие', null=True)),
                ('old_value', models.JSONField(blank=True, help_text='Состояние до изменения', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Состояние после изменения', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Кто выполнил действие. NULL — системное действие.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='users_audit_entity__318d4a_idx'), models.Index(fields=['user', '-created_at'], name='users_audit_user_id_949877_idx'), models.Index(fields=['-created_at'], name='users_audit_created_3a5128_idx')],
            },
        ),
    ]
