# Generated by Django 5.2.18 on 2026-10-09 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picking', '0001_initial'),
        ('samples', '0003_alter_sample_options_and_more'),
        ('storage', '0003_container_comment_container_comment_template_and_more'),
        ('work_orders', '0002_workorder_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EXPECTED', 'Ожидается'), ('IN_PROGRESS', 'В работе'), ('CONFIRMED', 'Подтверждена'), ('CANCELLED', 'Отменена')], default='EXPECTED', max_length=50)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_receipts', to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='samples.laboratory')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_receipts', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, help_text='Рейс-источник (INBOUND), если приёмка из рейса.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='picking.shipment')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='samples.site')),
            ],
            options={
                'verbose_name': 'Партия приёмки',
                'verbose_name_plural': 'Партии приёмки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/')),
                ('file_format', models.CharField(choices=[('XLSX', 'XLSX'), ('CSV', 'CSV')], default='XLSX', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PARSING', 'Парсинг'), ('PARSED', 'Распарсен'), ('ERROR', 'Ошибка'), ('APPLIED', 'Применён')], default='PARSING', max_length=50)),
                ('parse_errors', models.JSONField(blank=True, default=list, help_text='Список ошибок парсинга (строки, сообщения).')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, help_text='Созданная партия после применения импорта.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to='receiving.receipt')),
            ],
            options={
                'verbose_name': 'Сессия импорта',
                'verbose_name_plural': 'Сессии импорта',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_container_number', models.CharField(blank=True, default='', max_length=100)),
                ('expected_work_order_number', models.CharField(blank=True, default='', max_length=100)),
                ('expected_research_type_code', models.CharField(blank=True, default='', max_length=20)),
                ('expected_site_code', models.CharField(blank=True, default='', max_length=50)),
                ('expected_samples_count', models.IntegerField(blank=True, null=True)),
                ('actual_container_number', models.CharField(blank=True, default='', max_length=100)),
                ('actual_samples_count', models.IntegerField(blank=True, null=True)),
                ('scanned_barcodes', models.JSONField(blank=True, default=list, help_text='Список ШК проб, отсканированных при приёмке.')),
                ('status', models.CharField(choices=[('EXPECTED', 'Ожидается'), ('MATCHED', 'Совпадает'), ('DISCREPANCY', 'Расхождение'), ('MISSING', 'Отсутствует'), ('EXTRA', 'Лишняя'), ('PENDING_DECRYPTION', 'Ожидает расшифровки')], default='EXPECTED', max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('container', models.ForeignKey(blank=True, help_text='Создаётся при подтверждении приёмки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='storage.container')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receiving.receipt')),
                ('research_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='samples.researchtype')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='samples.site')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_items', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Строка приёмки',
                'verbose_name_plural': 'Строки приёмки',
                'ordering': ['receipt', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='receipt_number_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='receipt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['expected_date'], name='receipt_expected_idx'),
        ),
        migrations.AddIndex(
            model_name='importsession',
            index=models.Index(fields=['status'], name='import_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['receipt'], name='receipt_item_receipt_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['status'], name='receipt_item_status_idx'),
        ),
    ]
