# Generated by Django 5.2.18 on 2026-10-07 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_list_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ACTIVE', 'Активен'), ('COMPLETED', 'Завершён'), ('CANCELLED', 'Отменён')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pick_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список выборки',
                'verbose_name_plural': 'Списки выборки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('PICKED', 'Извлечена'), ('NOT_FOUND', 'Не найдена'), ('SENT', 'Отправлена')], default='PENDING', max_length=50)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('pick_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='picking.picklist')),
                ('picked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picked_items', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pick_items', to='samples.sample')),
            ],
            options={
                'verbose_name': 'Строка выборки',
                'verbose_name_plural': 'Строки выборки',
                'ordering': ['pick_list', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=100, unique=True)),
                ('destination', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_list_item', models.ForeignKey(blank=True, help_text='Если проба взята из списка выборки.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_items', to='picking.picklistitem')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='samples.sample')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='picking.shipment')),
            ],
            options={
                'verbose_name': 'Строка отправки',
                'verbose_name_plural': 'Строки отправки',
                'ordering': ['shipment', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='picklist',
            index=models.Index(fields=['status'], name='pick_list_status_idx'),
        ),
        migrations.AddIndex(
            model_name='picklist',
            index=models.Index(fields=['-created_at'], name='pick_list_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='picklistitem',
            constraint=models.UniqueConstraint(fields=('pick_list', 'sample'), name='pick_list_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='shipmentitem',
            constraint=models.UniqueConstraint(fields=('shipment', 'sample'), name='shipment_item_unique'),
        ),
    ]
