# Generated by Django 5.2.18 on 2026-10-09 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picking', '0001_initial'),
        ('samples', '0003_alter_sample_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='assembled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_shipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='direction',
            field=models.CharField(choices=[('OUTBOUND', 'Исходящая (мы → лаборатория)'), ('INBOUND', 'Входящая (лаборатория → мы)')], default='OUTBOUND', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='samples.laboratory'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='samples.site'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ASSEMBLED', 'Собран'), ('SENT', 'Отправлен'), ('RECEIVED', 'Принят'), ('PARTIALLY_RECEIVED', 'Принят с расхождениями'), ('RETURNED', 'Возвращён'), ('CANCELLED', 'Отменён'), ('LOST', 'Утерян')], default='SENT', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['direction'], name='shipment_direction_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='shipment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['laboratory'], name='shipment_laboratory_idx'),
        ),
    ]
