# Generated by Django 5.2.18 on 2026-10-07 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('full_address', models.CharField(help_text='Полный адрес: Комната / Стеллаж / Пролёт / Ярус / Ячейка', max_length=500, unique=True)),
                ('max_pallets', models.IntegerField(default=3)),
                ('qr_code', models.TextField(blank=True, help_text='Содержимое QR-кода, привязанного к ячейке', null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
                'ordering': ['tier', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_code', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.TextField(blank=True, null=True, unique=True)),
                ('position_in_cell', models.IntegerField(blank=True, help_text='Позиция поддона в ячейке: 1, 2 или 3', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('EMPTY', 'Пуст'), ('IN_TRANSIT', 'В пути')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallets', to='storage.cell')),
                ('floor_room', models.ForeignKey(blank=True, help_text='Комната, если поддон стоит прямо на полу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_pallets', to='storage.room')),
            ],
            options={
                'verbose_name': 'Поддон',
                'verbose_name_plural': 'Поддоны',
                'ordering': ['pallet_code'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='storage.room')),
            ],
            options={
                'verbose_name': 'Стеллаж',
                'verbose_name_plural': 'Стеллажи',
                'ordering': ['room', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=100, unique=True)),
                ('container_type', models.CharField(blank=True, default='', max_length=50)),
                ('qr_code', models.TextField(blank=True, null=True, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('IN_TRANSIT', 'В пути'), ('ISSUED', 'Выдана')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='storage.pallet')),
                ('floor_room', models.ForeignKey(blank=True, help_text='Комната, если тара стоит прямо на полу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_containers', to='storage.room')),
            ],
            options={
                'verbose_name': 'Тара',
                'verbose_name_plural': 'Тара',
                'ordering': ['container_number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='storage.rack')),
            ],
            options={
                'verbose_name': 'Пролёт',
                'verbose_name_plural': 'Пролёты',
                'ordering': ['rack', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('level_number', models.IntegerField(blank=True, help_text='Порядковый номер яруса (снизу вверх)', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='storage.section')),
            ],
            options={
                'verbose_name': 'Ярус',
                'verbose_name_plural': 'Ярусы',
                'ordering': ['section', 'level_number', 'code'],
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='storage.tier'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('room', 'code'), name='rack_unique_room_code'),
        ),
        migrations.AddConstraint(
            model_name='pallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cell__isnull', False), ('floor_room__isnull', True), ('position_in_cell__isnull', False)), models.Q(('cell__isnull', True), ('floor_room__isnull', False), ('position_in_cell__isnull', True)), models.Q(('cell__isnull', True), ('floor_room__isnull', True), ('position_in_cell__isnull', True)), _connector='OR'), name='pallet_location_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='pallet',
            constraint=models.CheckConstraint(condition=models.Q(('position_in_cell__isnull', True), models.Q(('position_in_cell__gte', 1), ('position_in_cell__lte', 3)), _connector='OR'), name='pallet_position_in_cell_range'),
        ),
        migrations.AddConstraint(
            model_name='container',
            constraint=models.CheckConstraint(condition=models.Q(('pallet__isnull', False), ('floor_room__isnull', False), _negated=True), name='container_not_on_pallet_and_floor'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('rack', 'code'), name='section_unique_rack_code'),
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='tier_unique_section_code'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('tier', 'code'), name='cell_unique_tier_code'),
        ),
    ]
