# Generated by Django 5.2.18 on 2026-10-07 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='1, 2 или 3', max_length=50)),
                ('full_address', models.CharField(help_text='Комната / Стеллаж / Секция / Ярус / Ячейка', max_length=500, unique=True)),
                ('cell_type', models.CharField(choices=[('STANDARD', 'Обычная'), ('CORE', 'Керновая')], default='STANDARD', max_length=20)),
                ('qr_code', models.TextField(blank=True, help_text='QR-код ячейки. Обязателен для точечной работы.', null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
                'ordering': ['tier', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('size_class', models.CharField(blank=True, default='', max_length=10)),
                ('max_on_standard_pallet', models.IntegerField(default=10, help_text='Максимум таких тар на стандартном поддоне.')),
                ('is_core', models.BooleanField(default=False, help_text='Задел: тип относится к керну.')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Тип тары',
                'verbose_name_plural': 'Типы тары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_type', models.CharField(choices=[('STANDARD', 'Обычный'), ('CORE', 'Керновый')], default='STANDARD', max_length=20)),
                ('capacity_override', models.JSONField(blank=True, default=dict, help_text='Переопределение вместимости на этом поддоне: {"container_type_id": max_count}. Если пусто — используется ContainerType.max_on_standard_pallet.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('EMPTY', 'Пуст'), ('IN_TRANSIT', 'В пути')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.OneToOneField(blank=True, help_text='Ячейка, где стоит поддон (1 ячейка = 1 поддон).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pallet', to='storage.cell')),
                ('floor_room', models.ForeignKey(blank=True, help_text='Комната, если поддон стоит прямо на полу.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_pallets', to='storage.room')),
            ],
            options={
                'verbose_name': 'Поддон',
                'verbose_name_plural': 'Поддоны',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='storage.room')),
            ],
            options={
                'verbose_name': 'Стеллаж',
                'verbose_name_plural': 'Стеллажи',
                'ordering': ['room', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=100, unique=True)),
                ('qr_code', models.TextField(blank=True, help_text='QR-код тары. Обязателен для приёмки/выборки.', null=True, unique=True)),
                ('position_on_pallet', models.IntegerField(blank=True, help_text='Позиция на поддоне (порядок сканирования). Опционально.', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('IN_TRANSIT', 'В пути'), ('ISSUED', 'Выдана')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='storage.containertype')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='storage.pallet')),
                ('floor_room', models.ForeignKey(blank=True, help_text='Комната, если тара стоит прямо на полу.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_containers', to='storage.room')),
            ],
            options={
                'verbose_name': 'Тара',
                'verbose_name_plural': 'Тара',
                'ordering': ['container_number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('qr_code', models.TextField(blank=True, help_text='QR-код секции (обязателен для виртуального вида).', null=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='storage.rack')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ['rack', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'A (нижний)'), ('B', 'B'), ('C', 'C'), ('D', 'D (верхний)')], max_length=1)),
                ('level_number', models.IntegerField(blank=True, help_text='1=A, 2=B, 3=C, 4=D', null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='storage.section')),
            ],
            options={
                'verbose_name': 'Ярус',
                'verbose_name_plural': 'Ярусы',
                'ordering': ['section', 'level_number'],
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='storage.tier'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('room', 'code'), name='rack_unique_room_code'),
        ),
        migrations.AddConstraint(
            model_name='pallet',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cell__isnull', False), ('floor_room__isnull', True)), models.Q(('cell__isnull', True), ('floor_room__isnull', False)), models.Q(('cell__isnull', True), ('floor_room__isnull', True)), _connector='OR'), name='pallet_location_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='container',
            constraint=models.CheckConstraint(condition=models.Q(('pallet__isnull', False), ('floor_room__isnull', False), _negated=True), name='container_not_on_pallet_and_floor'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('rack', 'code'), name='section_unique_rack_code'),
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='tier_unique_section_code'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(fields=('tier', 'code'), name='cell_unique_tier_code'),
        ),
    ]
