# Generated by Django 5.2.18 on 2026-10-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Например: «Повреждена», «Влажная».",
                        max_length=500,
                        unique=True,
                    ),
                ),
                ("sort_order", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Комментарий к таре",
                "verbose_name_plural": "Комментарии к таре",
                "ordering": ["sort_order", "text"],
            },
        ),
        migrations.AlterField(
            model_name="pallet",
            name="capacity_override",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Переопределение вместимости на этом поддоне: {"container_type_id": max_count}.',
            ),
        ),
        migrations.AlterField(
            model_name="tier",
            name="level_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
