# Generated by Django 5.2.18 on 2026-10-09 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_containercomment_alter_pallet_capacity_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Произвольный комментарий к таре.'),
        ),
        migrations.AddField(
            model_name='container',
            name='comment_template',
            field=models.ForeignKey(blank=True, help_text='Шаблон комментария (если выбран из списка).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='containers', to='storage.containercomment'),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активна'), ('PENDING_PLACEMENT', 'Ожидает размещения'), ('IN_TRANSIT', 'В пути'), ('ISSUED', 'Выдана')], default='ACTIVE', max_length=50),
        ),
    ]
