# Generated by Django 5.2.18 on 2026-10-09 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_alter_sample_options_and_more'),
        ('storage', '0003_container_comment_container_comment_template_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containertype',
            options={'ordering': ['laboratory', 'name'], 'verbose_name': 'Тип тары', 'verbose_name_plural': 'Типы тары'},
        ),
        migrations.AddField(
            model_name='containertype',
            name='laboratory',
            field=models.ForeignKey(blank=True, help_text='NULL — общий тип, доступный всем лабораториям.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container_types', to='samples.laboratory'),
        ),
        migrations.AlterField(
            model_name='containertype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='containertype',
            constraint=models.UniqueConstraint(fields=('name', 'laboratory'), name='container_type_unique_name_lab'),
        ),
    ]
