# Generated by Django 5.2.18 on 2026-10-07 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='DRAFT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_move_operations', to=settings.AUTH_USER_MODEL)),
                ('target_cell', models.ForeignKey(blank=True, help_text='Целевая ячейка.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_move_operations', to='storage.cell')),
                ('target_floor_room', models.ForeignKey(blank=True, help_text='Целевая комната (если на пол).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_move_operations', to='storage.room')),
            ],
            options={
                'verbose_name': 'Операция перемещения',
                'verbose_name_plural': 'Операции перемещения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoveOperationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('MOVED', 'Перемещён'), ('SKIPPED', 'Пропущен')], default='PENDING', max_length=50)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_items', to='storage.container')),
                ('move_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='movements.moveoperation')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_items', to='storage.pallet')),
                ('source_cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_move_items', to='storage.cell')),
                ('source_floor_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_move_items', to='storage.room')),
            ],
            options={
                'verbose_name': 'Строка перемещения',
                'verbose_name_plural': 'Строки перемещения',
                'ordering': ['move_operation', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='moveoperation',
            index=models.Index(fields=['status'], name='move_op_status_idx'),
        ),
        migrations.AddIndex(
            model_name='moveoperation',
            index=models.Index(fields=['-created_at'], name='move_op_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='moveoperation',
            constraint=models.CheckConstraint(condition=models.Q(('target_cell__isnull', False), ('target_floor_room__isnull', False), _negated=True), name='move_op_target_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='moveoperationitem',
            constraint=models.CheckConstraint(condition=models.Q(('pallet__isnull', False), ('container__isnull', False), _negated=True), name='move_item_pallet_xor_container'),
        ),
    ]
