# Generated by Django 5.2.18 on 2026-10-09 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0004_alter_containertype_options_containertype_laboratory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Номер партии печати, например ПЕЧ-2026-001.', max_length=100, unique=True)),
                ('print_type', models.CharField(choices=[('LABELS', 'Этикетки'), ('QR_ONLY', 'Только QR')], default='LABELS', help_text='Что печатаем: полные этикетки или только QR.', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('READY', 'Готов к печати'), ('PRINTED', 'Напечатан'), ('CANCELLED', 'Отменён')], default='DRAFT', max_length=20)),
                ('printed_at', models.DateTimeField(blank=True, help_text='Когда партия была напечатана.', null=True)),
                ('total_items', models.IntegerField(default=0, help_text='Сколько тар в партии (снимок на момент печати).')),
                ('total_pages', models.IntegerField(default=0, help_text='Сколько листов A4 требуется (снимок на момент печати).')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Кто создал партию печати.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_print_batches', to=settings.AUTH_USER_MODEL)),
                ('printed_by', models.ForeignKey(blank=True, help_text='Кто напечатал партию.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_print_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Партия печати',
                'verbose_name_plural': 'Партии печати',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Порядок тары в партии (для стабильной раскладки).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labels.printbatch')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_batch_items', to='storage.container')),
            ],
            options={
                'verbose_name': 'Элемент партии печати',
                'verbose_name_plural': 'Элементы партии печати',
                'ordering': ['batch', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'container'), name='print_batch_item_unique_batch_container')],
            },
        ),
    ]
