# Generated by Django 5.2.18 on 2026-10-07 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_name', models.CharField(max_length=150)),
                ('field_name', models.CharField(blank=True, default='', max_length=150)),
                ('cluster', models.CharField(blank=True, default='', max_length=100)),
                ('coordinates', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['well_name'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_number', models.CharField(help_text='Номер пробы. НЕ уникален — может повторяться для разных типов исследования.', max_length=100)),
                ('research_type', models.CharField(max_length=100)),
                ('depth_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('depth_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('site', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('IN_STORAGE', 'На хранении'), ('IN_TRANSIT', 'В пути'), ('ISSUED', 'Выдана'), ('CONSUMED', 'Израсходована'), ('DISPOSED', 'Утилизирована')], default='IN_STORAGE', max_length=50)),
                ('qr_code', models.TextField(blank=True, null=True, unique=True)),
                ('legacy_data', models.JSONField(blank=True, null=True)),
                ('disposed_at', models.DateTimeField(blank=True, help_text='Когда проба утилизирована.', null=True)),
                ('disposal_reason', models.TextField(blank=True, default='', help_text='Причина утилизации.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='storage.container')),
                ('current_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_samples', to='work_orders.workorder')),
                ('disposed_by', models.ForeignKey(blank=True, help_text='Кто утилизировал пробу.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_samples', to=settings.AUTH_USER_MODEL)),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='samples.well')),
            ],
            options={
                'verbose_name': 'Проба',
                'verbose_name_plural': 'Пробы',
                'ordering': ['sample_number', 'research_type'],
            },
        ),
        migrations.CreateModel(
            name='SampleWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_links', to='samples.sample')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_links', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Связь пробы с Н/З',
                'verbose_name_plural': 'Связи проб с Н/З',
                'ordering': ['-linked_at'],
                'constraints': [models.UniqueConstraint(fields=('sample', 'work_order'), name='sample_work_order_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['sample_number'], name='sample_number_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['research_type'], name='sample_research_type_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['container'], name='sample_container_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['current_work_order'], name='sample_work_order_idx'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['status'], name='sample_status_idx'),
        ),
    ]
