# Generated by Django 5.2.18 on 2026-10-08 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samples", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Код лаборатории: ЛАБ-1.", max_length=50, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название: «Лаборатория 1».", max_length=200
                    ),
                ),
                (
                    "prefixes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Префиксы проб. Пример: ["TAA-A", "TAA-B"].',
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Лаборатория",
                "verbose_name_plural": "Лаборатории",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ResearchType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Короткий код: ШЛ, ХА, ИЗ.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название: «Шлифы», «Хим. анализ».",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "sort_order",
                    models.IntegerField(
                        default=100, help_text="Порядок в списках (меньше — выше)."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Устаревшие скрываются из выпадающих списков.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип исследования",
                "verbose_name_plural": "Типы исследования",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Код участка: TST, СЕВ.", max_length=50, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название: «Тестовый участок».", max_length=200
                    ),
                ),
                (
                    "match_patterns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Паттерны для распознавания Н/З. Пример: ["TST", "Тест"].',
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Участок",
                "verbose_name_plural": "Участки",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.AlterField(
            model_name="sample",
            name="disposal_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sample",
            name="disposed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="disposed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disposed_samples",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sample",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_STORAGE", "На хранении"),
                    ("IN_TRANSIT", "В пути"),
                    ("ISSUED", "Выдана"),
                    ("CONSUMED", "Израсходована"),
                    ("DISPOSED", "Утилизирована"),
                    ("PENDING_DECRYPTION", "Ожидает расшифровки"),
                ],
                default="IN_STORAGE",
                max_length=50,
            ),
        ),
    ]
