# Generated by Django 5.2.18 on 2026-10-09 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_laboratory_researchtype_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['sample_number', 'research_type__code'], 'verbose_name': 'Проба', 'verbose_name_plural': 'Пробы'},
        ),
        migrations.RemoveIndex(
            model_name='sample',
            name='sample_research_type_idx',
        ),
        migrations.AlterField(
            model_name='sample',
            name='research_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='samples.researchtype'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='samples.site'),
        ),
    ]
